export const images = [
  {
    id: 'YdAqiUkUoWA',
    name: 'cat-1',
    url: 'img/cats-1.jpg',
    description: 'pink petaled flower',
    type: 'image',
  },
  {
    id: 'hX_hf2lPpUU',
    name: 'cat-2',
    url: 'img/cats-2.jpg',
    description: 'green leaf',
    type: 'image',
  },
  {
    id: 'w1JE5duY62M',
    name: 'cat-3',
    url: 'img/cats-3.jpg',
    description: 'red and white petaled flower close-up photography',
    type: 'image',
  },
  {
    id: '3tYZjGSBwbk',
    name: 'cat-4',
    url: 'img/cats-4.jpg',
    description: 'white daisy in bloom during daytime',
    type: 'image',
  },
  {
    id: 'NoXUQ54pDac',
    name: 'cat-5',
    url: 'img/cats-5.jpg',
    description: 'white-and-pink flowers',
    type: 'image',
  },
  {
    id: 'OZhYgZh0bAg',
    name: 'cat-6',
    url: 'img/cats-6.jpg',
    description: 'white and purple flower petals',
    type: 'image',
  },
  {
    id: 'YdAqiUkUoWA1',
    name: 'cat-1',
    url: 'img/cats-1.jpg',
    description: 'pink petaled flower',
    type: 'image',
  },
  {
    id: 'hX_hf2lPpUU1',
    name: 'cat-2',
    url: 'img/cats-2.jpg',
    description: 'green leaf',
    type: 'image',
  },
  {
    id: 'w1JE5duY62M1',
    name: 'cat-3',
    url: 'img/cats-3.jpg',
    description: 'red and white petaled flower close-up photography',
    type: 'image',
  },
  {
    id: '3tYZjGSBwbk1',
    name: 'cat-4',
    url: 'img/cats-4.jpg',
    description: 'white daisy in bloom during daytime',
    type: 'image',
  },
  {
    id: 'NoXUQ54pDac1',
    name: 'cat-5',
    url: 'img/cats-5.jpg',
    description: 'white-and-pink flowers',
    type: 'image',
  },
  {
    id: 'OZhYgZh0bAg1',
    name: 'cat-6',
    url: 'img/cats-6.jpg',
    description: 'white and purple flower petals',
    type: 'image',
  },
];
